### ISSUE TITLE
still problem with running the script

### ISSUE THREAD

**Issue by swiezaczek** [chedieck/telox#3]
I installed python 3.10 per instructions [https://aruljohn.com/blog/python-raspberrypi/ ](https://aruljohn.com/blog/python-raspberrypi/), but it doesnt seem to work despite it shows 3.10.7 version is installed.

```
pi@raspberrypi:~/Desktop/telox-master $ python bot.py
Traceback (most recent call last):
  File "/home/pi/Desktop/telox-master/bot.py", line 1, in <module>
    from core import Watcher
  File "/home/pi/Desktop/telox-master/core.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
pi@raspberrypi:~/Desktop/telox-master $ python3.10 bot.py
Traceback (most recent call last):
  File "/home/pi/Desktop/telox-master/bot.py", line 1, in <module>
    from core import Watcher
  File "/home/pi/Desktop/telox-master/core.py", line 1, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
pi@raspberrypi:~/Desktop/telox-master $ python3 bot.py
Traceback (most recent call last):
  File "/home/pi/Desktop/telox-master/bot.py", line 1, in <module>
    from core import Watcher
  File "/home/pi/Desktop/telox-master/core.py", line 117, in <module>
    def parse_price(price: str | None) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```

```

pi@raspberrypi:~/Desktop/telox-master $ python -V
Python 3.10.7
pi@raspberrypi:~/Desktop/telox-master $ pip --version
pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
```

```
pi@raspberrypi:~/Desktop/telox-master $ pip install -r requirements.txt
^[[A^[[ALooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: python-telegram-bot in /home/pi/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (20.1)
Requirement already satisfied: bs4 in /home/pi/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->-r requirements.txt (line 2)) (4.9.3)
Requirement already satisfied: httpx[http2]~=0.23.3 in /home/pi/.local/lib/python3.9/site-packages (from python-telegram-bot->-r requirements.txt (line 1)) (0.23.3)
Requirement already satisfied: sniffio in /home/pi/.local/lib/python3.9/site-packages (from httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (2020.6.20)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in /home/pi/.local/lib/python3.9/site-packages (from httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (0.16.3)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /home/pi/.local/lib/python3.9/site-packages (from httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: h2<5,>=3 in /home/pi/.local/lib/python3.9/site-packages (from httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (4.1.0)
Requirement already satisfied: hyperframe<7,>=6.0 in /home/pi/.local/lib/python3.9/site-packages (from h2<5,>=3->httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: hpack<5,>=4.0 in /home/pi/.local/lib/python3.9/site-packages (from h2<5,>=3->httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (4.0.0)
Requirement already satisfied: h11<0.15,>=0.13 in /home/pi/.local/lib/python3.9/site-packages (from httpcore<0.17.0,>=0.15.0->httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /home/pi/.local/lib/python3.9/site-packages (from httpcore<0.17.0,>=0.15.0->httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (3.6.2)
Requirement already satisfied: idna>=2.8 in /usr/lib/python3/dist-packages (from anyio<5.0,>=3.0->httpcore<0.17.0,>=0.15.0->httpx[http2]~=0.23.3->python-telegram-bot->-r requirements.txt (line 1)) (2.10)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->bs4->-r requirements.txt (line 2)) (2.2.1)
```

pip3.10 install -r requirements.txt:

```
pi@raspberrypi:~/Desktop/telox-master $ pip3.10 install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
Could not fetch URL https://pypi.org/simple/python-telegram-bot/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/python-telegram-bot/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/python-telegram-bot/
Could not fetch URL https://www.piwheels.org/simple/python-telegram-bot/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/python-telegram-bot/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement python-telegram-bot (from versions: none)
ERROR: No matching distribution found for python-telegram-bot
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://www.piwheels.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='www.piwheels.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: There was an error checking the latest version of pip.
```

**Comment by chedieck** [comment]
Your error has nothing to do with this repo, it has to with the python SSL module not being available. You are probably missing `openssl` or `openssl-devel` packages.

Closing this again, as it does not concern errors in the repository.
