### ISSUE TITLE
está dando erro pois mudou a engine do olx no ultimo mes

### ISSUE THREAD

**Issue by FernandoGiovannini** [chedieck/telox#4]
o melhor scrapper que usei, mas parou de funcionar pois mudou a engine do olx no ultimo mes

C:\Users\Fernando\Desktop\telox-master>python bot.py
Ativado.
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Fernando\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\telegram\ext\_application.py", line 1173, in process_update
    await coroutine
  File "C:\Users\Fernando\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\telegram\ext\_basehandler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Fernando\Desktop\telox-master\bot.py", line 56, in start
    [w.update() for w in WATCHER_LIST]
  File "C:\Users\Fernando\Desktop\telox-master\bot.py", line 56, in <listcomp>
    [w.update() for w in WATCHER_LIST]
     ^^^^^^^^^^
  File "C:\Users\Fernando\Desktop\telox-master\core.py", line 173, in update
    data_json = json.loads(next((s for s in scripts if s.has_attr('data-json')), None)['data-json'])
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by chedieck** [comment]
Opa, acabei de perceber e consertar esse bug aí, por favor dizer se está funcionando pra você também.
